stages:
  - test
  - deploy

quality_and_tests:
  image: python:3.6
  stage: test
  before_script:
    - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/.local/bin

  script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - flake8
#    - scrapy check
    - cd house_finder && python manage.py behave --settings=house_finder.settings.local

.deploy_setup: &deploy_before_scripts
  before_script:
    - mkdir ~/.ssh
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - touch ~/.ssh/known_hosts
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - cd deploy_tools
    - echo ${ANSIBLE_VAULT_SECRET} > .vault_password.txt
    - pip install ansible

deploy_staging:
  image: ansible/ansible:default
  stage: deploy
  <<: *deploy_before_scripts
  script:
    - ansible-playbook playbook.yml -i hosts/staging/inventory --vault-password-file .vault_password.txt
  environment:
    name: Staging
    url: https://houses-staging.ariasmonche.es
  only:
  - develop

deploy_live:
  image: ansible/ansible:default
  stage: deploy
  <<: *deploy_before_scripts
  script:
    - ansible-playbook playbook.yml -i hosts/live/inventory --vault-password-file .vault_password.txt
  environment:
    name: Live
    url: https://houses.ariasmonche.es
  only:
  - master