stages:
  - test
  - deploy

quality:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements_quality.txt
  script:
    - flake8

bdd_tests:
  image: registry.gitlab.com/eduarias/home_crawler/bdd_tests
  stage: test
  before_script:
    # Install chrome
#    - curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
#    - apt update && apt install -y google-chrome-stable
    # Install chromedriver
#    - apt install unzip
#    - wget -q https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -O /tmp/chromedriver.zip
#    - unzip /tmp/chromedriver.zip -d /usr/local/bin
    #- wget -q https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz -P /tmp
    #- tar xvzf /tmp/geckodriver-*.tar.gz -C /usr/local/bin/
  script:
    - pip3 install -r requirements.txt
    - pip3 install -r requirements_test.txt
#    - scrapy check
    - cd house_finder && python3 manage.py behave --settings=house_finder.settings.local

.deploy_setup: &deploy_before_scripts
  before_script:
    - mkdir ~/.ssh
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - touch ~/.ssh/known_hosts
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - cd deploy_tools
    - echo ${ANSIBLE_VAULT_SECRET} > .vault_password.txt
    - pip install ansible

deploy_staging:
  image: ansible/ansible:default
  stage: deploy
  <<: *deploy_before_scripts
  script:
    - ansible-playbook playbook.yml -i hosts/staging/inventory --vault-password-file .vault_password.txt
  environment:
    name: Staging
    url: https://houses-staging.ariasmonche.es
  only:
  - develop

deploy_live:
  image: ansible/ansible:default
  stage: deploy
  <<: *deploy_before_scripts
  script:
    - ansible-playbook playbook.yml -i hosts/live/inventory --vault-password-file .vault_password.txt
  environment:
    name: Live
    url: https://houses.ariasmonche.es
  only:
  - master