stages:
  - test
  - deploy

#quality:
#  image: python:3.6
#  stage: test
#  script:
#    - pip install -r requirements.txt
#    - pip install -r requirements_test.txt
#    - flake8
##    - scrapy check

deploy_staging:
  image: ansible/ansible:default
  stage: deploy
  script:
    - pip install ansible
    - mkdir -p /root/.ssh
    - echo ${SSH_PRIVATE_KEY} > /root/.ssh/id_rsa
    - cat /root/.ssh/id_rsa
    - cd deploy_tools
    - echo ${ANSIBLE_VAULT_SECRET} > .vault_password.txt
    - ansible-playbook playbook.yml -i hosts/staging/inventory --vault-password-file .vault_password.txt
  environment:
    name: Staging
    url: https://houses.staging.ariasmonche.es
  only:
  - develop
