version: '3'

services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
  web:
    build: ./house_finder
    command: ["./docker-entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SU_USERNAME="admin"
      - DJANGO_SU_EMAIL="eduarias@users.noreply.github.com"
      - DJANGO_SU_PASSWORD="test"
  crawler:
    build: .
    command: ["python", "home_crawler.py"]
    depends_on:
      - db