version: '3'

services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
  web:
    build: ./house_finder
    command: ["./docker-entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db