---
# tasks file for eduarias.python

- name: Install Python 3 environment
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
     - python3
     - python3-venv
     - python3-dev
    state: present
  become: true
  become_method: sudo