# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.City')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('price', models.IntegerField(null=True)),
                ('url', models.URLField(unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('sqft_m2', models.IntegerField(null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('baths', models.IntegerField(null=True)),
                ('article_update_date', models.CharField(max_length=100)),
                ('is_interesting', models.BooleanField(default=False)),
                ('is_discard', models.BooleanField(default=False)),
                ('has_seen', models.BooleanField(default=False)),
                ('notes', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('last_view_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousesProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.District')),
            ],
        ),
        migrations.CreateModel(
            name='StartURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Rent'), ('B', 'Buy')], default='R', max_length=1)),
                ('url', models.URLField(unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.City')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.District')),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.Neighborhood')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.HousesProvider')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='start_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.StartURL'),
        ),
    ]
