# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
                ('price', models.IntegerField(null=True)),
                ('url', models.URLField(unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('sqft_m2', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('article_update_date', models.CharField(max_length=100)),
                ('is_interesting', models.BooleanField(default=False)),
                ('is_discard', models.BooleanField(default=False)),
                ('has_seen', models.BooleanField(default=False)),
                ('notes', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set([('site_id', 'website')]),
        ),
    ]
