# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousesProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.HousesProvider')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='house',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='house',
            name='website',
        ),
        migrations.AddField(
            model_name='house',
            name='start_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.StartURL'),
        ),
    ]
