# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20171001_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='last_view_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='baths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='sqft_m2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
