---
- name: Install Python 3 environment
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
     - python3
     - python3-venv
     - python3-dev
     - python3-pip
    state: present
  become: true